<?php
$sec = 'integration';
$extra_title .= 'Integration';
$headers[$sec] = array("Integration","A quick How-To on how to implement your news page(s) into your website.");

$h_content[$sec][] = array(1,"What is the integration function?","
	The integration function found in Settings -> Integration. Now what does it do? Because you want to show your news somewhere you can use the news_show.php file that we provide. The integration function generates the PHP code required to load NewsOffice into your website.<br> 
	
");
$h_content[$sec][] = array(1,"Generating and integrating the code.","
	When you have generated the code copy and paste it into your website on the location you want to display your news.<br>
	<br>
	When integrating the code:<br>
	<div class='important'>The code you generate must:<br>
		<ul>
			<li>Be placed in a .php file or file that is parsed as PHP coding.</li>
			<li>Be placed on the same web- server/site as your installation of NewsOffice.</li>
		</ul>
	</div>
");
$h_content[$sec][] = array(1,"\"Additional\" options","
	When you are on the integration function page you can see there are a couple of options which you can change. These options are described below.
");
$h_content[$sec][] = array(2,"NewsOffice directory","
	The directory that is already in the textfield is the directory generated by PHP realpath(), it is not 100% sure this is correct. Check if this is correct on your website or ask you webhosting if this is a correct path.<br>
	<br>
	The directory you enter must be the correct directory of the NewsOffice installation.<br>
	<br>
	The path PHP generates is the full path from the root of the server and not all directories might be visible for you.
");
$h_content[$sec][] = array(2,"Category","
	You might not want to display all your news on one news page, this is why you can use categories to devide it into smaller pages. Select the category you want display and only news added to that category will be displayed.<br>
	The default option is to display all news.
");
$h_content[$sec][] = array(2,"Theme","
	You can create different themes in the Manager -> Themes section. You can choose which theme to use on which news page. The code you will generate will than hold a new value which selects which theme to use.
");
?>